// <auto-generated/>

using System;

namespace OneBarker.CopyCodeGenerators.Samples;

#nullable enable
#pragma warning disable CS0109  // the member does not hide an inherited member.

partial class Mike
{
    /// <summary>
    /// Transforms the ValueToCopy value before assigning the value to the target.
    /// </summary>
    static partial void UpdateFromTransform_ValueToCopy(ref int value);

    /// <summary>
    /// Method to run before the UpdateFrom method begins copying values.
    /// </summary>
    partial void BeforeUpdateFrom(Mike source, ref int changeCount);

    /// <summary>
    /// Method to run after the UpdateFrom method finishes copying values.
    /// </summary>
    partial void AfterUpdateFrom(Mike source, ref int changeCount);

    /// <summary>
    /// Updates properties from the source object to this object and returns the number of changes.
    /// </summary>
    public new int UpdateFrom(Mike source)
    {
        if (ReferenceEquals(null, source)) throw new ArgumentNullException();
        if (ReferenceEquals(this, source)) return 0;
        var changeCount = 0;
        BeforeUpdateFrom(source, ref changeCount);
        var this_ValueToCopy = this.ValueToCopy;
        var source_ValueToCopy = source.ValueToCopy;
        UpdateFromTransform_ValueToCopy(ref source_ValueToCopy);
        if (!this_ValueToCopy.Equals(source_ValueToCopy)) {
            this.ValueToCopy = source_ValueToCopy;
            changeCount++;
        }
        AfterUpdateFrom(source, ref changeCount);
        return changeCount;
    }

    /// <summary>
    /// Method to run before the UpdateFrom method begins copying values.
    /// </summary>
    partial void BeforeUpdateFrom(OneBarker.CopyCodeGenerators.Samples.Mike2 source, ref int changeCount);

    /// <summary>
    /// Method to run after the UpdateFrom method finishes copying values.
    /// </summary>
    partial void AfterUpdateFrom(OneBarker.CopyCodeGenerators.Samples.Mike2 source, ref int changeCount);

    /// <summary>
    /// Updates properties from the source object to this object and returns the number of changes.
    /// </summary>
    public new int UpdateFrom(OneBarker.CopyCodeGenerators.Samples.Mike2 source)
    {
        if (ReferenceEquals(null, source)) throw new ArgumentNullException();
        if (ReferenceEquals(this, source)) return 0;
        var changeCount = 0;
        BeforeUpdateFrom(source, ref changeCount);
        var this_ValueToCopy = this.ValueToCopy;
        var source_ValueToCopy = source.ValueToCopy;
        UpdateFromTransform_ValueToCopy(ref source_ValueToCopy);
        if (!this_ValueToCopy.Equals(source_ValueToCopy)) {
            this.ValueToCopy = source_ValueToCopy;
            changeCount++;
        }
        AfterUpdateFrom(source, ref changeCount);
        return changeCount;
    }
}
