// <auto-generated/>

using System;

namespace Namespace1;

#nullable enable
#pragma warning disable CS0109  // the member does not hide an inherited member.

partial class Charlie
{
    /// <summary>
    /// Transforms the Alpha value before assigning the value to the target.
    /// </summary>
    static partial void CopyFromTransform_Alpha(ref int value);

    /// <summary>
    /// Method to run before the CopyFrom method begins copying values.
    /// </summary>
    partial void BeforeCopyFrom(Namespace2.Charlie source);

    /// <summary>
    /// Method to run after the CopyFrom method finishes copying values.
    /// </summary>
    partial void AfterCopyFrom(Namespace2.Charlie source);

    /// <summary>
    /// Copies properties from the source object to this object and returns this object.
    /// </summary>
    public new Charlie CopyFrom(Namespace2.Charlie source)
    {
        if (ReferenceEquals(null, source)) throw new ArgumentNullException();
        if (ReferenceEquals(this, source)) return this;
        BeforeCopyFrom(source);
        var source_Alpha = source.Alpha;
        CopyFromTransform_Alpha(ref source_Alpha);
        this.Alpha = source_Alpha;
        AfterCopyFrom(source);
        return this;
    }
}
