// <auto-generated/>

using System;

namespace OneBarker.CopyCodeGenerators.Samples;

#nullable enable
#pragma warning disable CS0109  // the member does not hide an inherited member.

partial class Lima
{
    /// <summary>
    /// Transforms the Value value before assigning the value to the target.
    /// </summary>
    static partial void UpdateTargetTransform_Value(ref int value);

    /// <summary>
    /// Method to run before the UpdateTarget method begins copying values.
    /// </summary>
    partial void BeforeUpdateTarget(OneBarker.CopyCodeGenerators.Samples.Lima2 target, ref int changeCount);

    /// <summary>
    /// Method to run after the UpdateTarget method finishes copying values.
    /// </summary>
    partial void AfterUpdateTarget(OneBarker.CopyCodeGenerators.Samples.Lima2 target, ref int changeCount);

    /// <summary>
    /// Updates properties in the target object from this object and returns the number of changes.
    /// </summary>
    public new int UpdateTarget(OneBarker.CopyCodeGenerators.Samples.Lima2 target)
    {
        if (ReferenceEquals(null, target)) throw new ArgumentNullException();
        if (ReferenceEquals(this, target)) return 0;
        var changeCount = 0;
        BeforeUpdateTarget(target, ref changeCount);
        var target_Value = target.Value;
        var this_Value = this.Value;
        UpdateTargetTransform_Value(ref this_Value);
        if (!target_Value.Equals(this_Value)) {
            target.Value = this_Value;
            changeCount++;
        }
        AfterUpdateTarget(target, ref changeCount);
        return changeCount;
    }

    /// <summary>
    /// Method to run before the UpdateTarget method begins copying values.
    /// </summary>
    partial void BeforeUpdateTarget(ref OneBarker.CopyCodeGenerators.Samples.Lima3 target, ref int changeCount);

    /// <summary>
    /// Method to run after the UpdateTarget method finishes copying values.
    /// </summary>
    partial void AfterUpdateTarget(ref OneBarker.CopyCodeGenerators.Samples.Lima3 target, ref int changeCount);

    /// <summary>
    /// Updates properties in the target object from this object and returns the number of changes.
    /// </summary>
    public new int UpdateTarget(ref OneBarker.CopyCodeGenerators.Samples.Lima3 target)
    {
        if (ReferenceEquals(null, target)) throw new ArgumentNullException();
        if (ReferenceEquals(this, target)) return 0;
        var changeCount = 0;
        BeforeUpdateTarget(ref target, ref changeCount);
        var target_Value = target.Value;
        var this_Value = this.Value;
        UpdateTargetTransform_Value(ref this_Value);
        if (!target_Value.Equals(this_Value)) {
            target.Value = this_Value;
            changeCount++;
        }
        AfterUpdateTarget(ref target, ref changeCount);
        return changeCount;
    }
}
