// <auto-generated/>

using System;

namespace OneBarker.CopyCodeGenerators.Samples;

#nullable enable
#pragma warning disable CS0109  // the member does not hide an inherited member.

partial class Uniform
{
    /// <summary>
    /// Transforms the Alpha value before assigning the value to the target.
    /// </summary>
    static partial void CopyFromTransform_Alpha(ref int value);

    /// <summary>
    /// Transforms the Bravo value before assigning the value to the target.
    /// </summary>
    static partial void CopyFromTransform_Bravo(ref int value);

    /// <summary>
    /// Transforms the Charlie value before assigning the value to the target.
    /// </summary>
    static partial void CopyFromTransform_Charlie(ref int value);

    /// <summary>
    /// Transforms the Delta value before assigning the value to the target.
    /// </summary>
    static partial void CopyFromTransform_Delta(ref int value);

    /// <summary>
    /// Method to run before the CopyFrom method begins copying values.
    /// </summary>
    partial void BeforeCopyFrom(OneBarker.CopyCodeGenerators.Samples.Uniform1 source);

    /// <summary>
    /// Method to run after the CopyFrom method finishes copying values.
    /// </summary>
    partial void AfterCopyFrom(OneBarker.CopyCodeGenerators.Samples.Uniform1 source);

    /// <summary>
    /// Copies properties from the source object to this object and returns this object.
    /// </summary>
    public new Uniform CopyFrom(OneBarker.CopyCodeGenerators.Samples.Uniform1 source)
    {
        if (ReferenceEquals(null, source)) throw new ArgumentNullException();
        if (ReferenceEquals(this, source)) return this;
        BeforeCopyFrom(source);
        var source_Alpha = source.Alpha;
        CopyFromTransform_Alpha(ref source_Alpha);
        this.Alpha = source_Alpha;
        var source_Bravo = source.Bravo;
        CopyFromTransform_Bravo(ref source_Bravo);
        this.Bravo = source_Bravo;
        var source_Charlie = source.Charlie;
        CopyFromTransform_Charlie(ref source_Charlie);
        this._charlie = source_Charlie;
        var source_Delta = source.Delta;
        CopyFromTransform_Delta(ref source_Delta);
        this.Delta = source_Delta;
        AfterCopyFrom(source);
        return this;
    }
}
