// <auto-generated/>

using System;

namespace TestNamespace;

#nullable enable
#pragma warning disable CS0109  // the member does not hide an inherited member.

partial class Alpha
{
    /// <summary>
    /// Transforms the Value value before assigning the value to the target.
    /// </summary>
    static partial void ConstructTransform_Value(ref int value);

    /// <summary>
    /// Method to run after the Construct method finishes copying values.
    /// </summary>
    partial void AfterConstruct(Alpha source);

    /// <summary>
    /// Creates an instance of Alpha with values from the provided object.
    /// </summary>
    public Alpha(Alpha source) : this()
    {
        if (ReferenceEquals(null, source)) return;
        var source_Value = source.Value;
        ConstructTransform_Value(ref source_Value);
        this.Value = source_Value;
        AfterConstruct(source);
    }
}
