// <auto-generated/>

using System;

namespace TestNamespace;

#nullable enable
#pragma warning disable CS0109  // the member does not hide an inherited member.

partial class Alpha
{
    /// <summary>
    /// Transforms the Value value before assigning the value to the target.
    /// </summary>
    static partial void CopyFromTransform_Value(ref int value);

    /// <summary>
    /// Method to run before the CopyFrom method begins copying values.
    /// </summary>
    partial void BeforeCopyFrom(Alpha source);

    /// <summary>
    /// Method to run after the CopyFrom method finishes copying values.
    /// </summary>
    partial void AfterCopyFrom(Alpha source);

    /// <summary>
    /// Copies properties from the source object to this object and returns this object.
    /// </summary>
    public new Alpha CopyFrom(Alpha source)
    {
        if (ReferenceEquals(null, source)) throw new ArgumentNullException();
        if (ReferenceEquals(this, source)) return this;
        BeforeCopyFrom(source);
        var source_Value = source.Value;
        CopyFromTransform_Value(ref source_Value);
        this.Value = source_Value;
        AfterCopyFrom(source);
        return this;
    }
}
