// <auto-generated/>

using System;

namespace OneBarker.CopyCodeGenerators.Samples;

#nullable enable
#pragma warning disable CS0109  // the member does not hide an inherited member.

partial record struct Kilo
{
    /// <summary>
    /// Transforms the Name value and returns the new value.
    /// </summary>
    static string? PassthroughTransform_Name(OneBarker.CopyCodeGenerators.Samples.Kilo2 source)
    {
        if (ReferenceEquals(null, source)) throw new ArgumentNullException();
        var value = source.Name;
        ConstructTransform_Name(ref value);
        return value;
    }

    /// <summary>
    /// Transforms the X value and returns the new value.
    /// </summary>
    static float PassthroughTransform_X(OneBarker.CopyCodeGenerators.Samples.Kilo2 source)
    {
        if (ReferenceEquals(null, source)) throw new ArgumentNullException();
        var value = source.X;
        ConstructTransform_X(ref value);
        return value;
    }

    /// <summary>
    /// Transforms the Y value and returns the new value.
    /// </summary>
    static float PassthroughTransform_Y(OneBarker.CopyCodeGenerators.Samples.Kilo2 source)
    {
        if (ReferenceEquals(null, source)) throw new ArgumentNullException();
        var value = source.Y;
        ConstructTransform_Y(ref value);
        return value;
    }

    /// <summary>
    /// Transforms the Name value before assigning the value to the target.
    /// </summary>
    static partial void ConstructTransform_Name(ref string? value);

    /// <summary>
    /// Transforms the X value before assigning the value to the target.
    /// </summary>
    static partial void ConstructTransform_X(ref float value);

    /// <summary>
    /// Transforms the Y value before assigning the value to the target.
    /// </summary>
    static partial void ConstructTransform_Y(ref float value);

    /// <summary>
    /// Method to run after the Construct method finishes copying values.
    /// </summary>
    partial void AfterConstruct(OneBarker.CopyCodeGenerators.Samples.Kilo2 source);

    /// <summary>
    /// Creates an instance of Kilo with values from the provided object.
    /// </summary>
    public Kilo(OneBarker.CopyCodeGenerators.Samples.Kilo2 source) : this(PassthroughTransform_X(source), PassthroughTransform_Y(source), PassthroughTransform_Name(source))
    {
        if (ReferenceEquals(null, source)) throw new ArgumentNullException();
        AfterConstruct(source);
    }
}
