// <auto-generated/>

using System;

namespace OneBarker.CopyCodeGenerators.Samples;

#nullable enable
#pragma warning disable CS0109  // the member does not hide an inherited member.

partial class Uniform
{
    /// <summary>
    /// Transforms the Alpha value before assigning the value to the target.
    /// </summary>
    static partial void CopyToTransform_Alpha(ref int value);

    /// <summary>
    /// Transforms the Bravo value before assigning the value to the target.
    /// </summary>
    static partial void CopyToTransform_Bravo(ref int value);

    /// <summary>
    /// Transforms the Charlie value before assigning the value to the target.
    /// </summary>
    static partial void CopyToTransform_Charlie(ref int value);

    /// <summary>
    /// Transforms the Delta value before assigning the value to the target.
    /// </summary>
    static partial void CopyToTransform_Delta(ref int value);

    /// <summary>
    /// Method to run before the CopyTo method begins copying values.
    /// </summary>
    partial void BeforeCopyTo(OneBarker.CopyCodeGenerators.Samples.Uniform1 target);

    /// <summary>
    /// Method to run after the CopyTo method finishes copying values.
    /// </summary>
    partial void AfterCopyTo(OneBarker.CopyCodeGenerators.Samples.Uniform1 target);

    /// <summary>
    /// Copies properties from this object to the target object and returns the target object.
    /// </summary>
    public new Uniform CopyTo(OneBarker.CopyCodeGenerators.Samples.Uniform1 target)
    {
        if (ReferenceEquals(null, target)) throw new ArgumentNullException();
        BeforeCopyTo(target);
        var this_Alpha = this.Alpha;
        CopyToTransform_Alpha(ref this_Alpha);
        target.Alpha = this_Alpha;
        var this_Bravo = this.Bravo;
        CopyToTransform_Bravo(ref this_Bravo);
        target.Bravo = this_Bravo;
        var this_Charlie = this._charlie;
        CopyToTransform_Charlie(ref this_Charlie);
        target.Charlie = this_Charlie;
        var this_Delta = this.Get_Delta();
        CopyToTransform_Delta(ref this_Delta);
        target.Delta = this_Delta;
        AfterCopyTo(target);
        return this;
    }
}
