// <auto-generated/>

using System;

namespace Namespace1;

#nullable enable
#pragma warning disable CS0109  // the member does not hide an inherited member.

partial class Charlie
{
    /// <summary>
    /// Transforms the Alpha value before assigning the value to the target.
    /// </summary>
    static partial void UpdateFromTransform_Alpha(ref int value);

    /// <summary>
    /// Method to run before the UpdateFrom method begins copying values.
    /// </summary>
    partial void BeforeUpdateFrom(Namespace2.Charlie source, ref int changeCount);

    /// <summary>
    /// Method to run after the UpdateFrom method finishes copying values.
    /// </summary>
    partial void AfterUpdateFrom(Namespace2.Charlie source, ref int changeCount);

    /// <summary>
    /// Updates properties from the source object to this object and returns the number of changes.
    /// </summary>
    public new int UpdateFrom(Namespace2.Charlie source)
    {
        if (ReferenceEquals(null, source)) throw new ArgumentNullException();
        if (ReferenceEquals(this, source)) return 0;
        var changeCount = 0;
        BeforeUpdateFrom(source, ref changeCount);
        var this_Alpha   = this.Alpha;
        var source_Alpha = source.Alpha;
        UpdateFromTransform_Alpha(ref source_Alpha);
        if (!this_Alpha.Equals(source_Alpha)) {
            this.Alpha = source_Alpha;
            changeCount++;
        }
        AfterUpdateFrom(source, ref changeCount);
        return changeCount;
    }
}
