// <auto-generated/>

using System;

namespace OneBarker.CopyCodeGenerators.Samples;

#nullable enable
#pragma warning disable CS0109  // the member does not hide an inherited member.

partial class Quebec
{
    /// <summary>
    /// Transforms the W value before assigning the value to the target.
    /// </summary>
    partial void UpdateExternalTransform_W(ref int value);

    /// <summary>
    /// Transforms the X value before assigning the value to the target.
    /// </summary>
    partial void UpdateExternalTransform_X(ref int value);

    /// <summary>
    /// Transforms the Y value before assigning the value to the target.
    /// </summary>
    partial void UpdateExternalTransform_Y(ref int value);

    /// <summary>
    /// Method to run before the UpdateExternal method begins copying values.
    /// </summary>
    partial void BeforeUpdateExternal(OneBarker.CopyCodeGenerators.Samples.QuebecSource source, OneBarker.CopyCodeGenerators.Samples.QuebecTarget target, ref int changeCount);

    /// <summary>
    /// Method to run after the UpdateExternal method finishes copying values.
    /// </summary>
    partial void AfterUpdateExternal(OneBarker.CopyCodeGenerators.Samples.QuebecSource source, OneBarker.CopyCodeGenerators.Samples.QuebecTarget target, ref int changeCount);

    /// <summary>
    /// Updates properties from the source object to the target object and returns the number of changes.
    /// </summary>
    public new int UpdateExternal(OneBarker.CopyCodeGenerators.Samples.QuebecSource source, OneBarker.CopyCodeGenerators.Samples.QuebecTarget target)
    {
        if (ReferenceEquals(null, source)) throw new ArgumentNullException();
        if (ReferenceEquals(null, target)) throw new ArgumentNullException();
        if (ReferenceEquals(target, source)) return 0;
        var changeCount = 0;
        BeforeUpdateExternal(source, target, ref changeCount);
        var target_W = target.W;
        var source_W = source.W;
        UpdateExternalTransform_W(ref source_W);
        if (!target_W.Equals(source_W)) {
            target.W = source_W;
            changeCount++;
        }
        var target_X = target.X;
        var source_X = source.X;
        UpdateExternalTransform_X(ref source_X);
        if (!target_X.Equals(source_X)) {
            target.X = source_X;
            changeCount++;
        }
        var target_Y = target.Y;
        var source_Y = source.Y;
        UpdateExternalTransform_Y(ref source_Y);
        if (!target_Y.Equals(source_Y)) {
            target.Y = source_Y;
            changeCount++;
        }
        AfterUpdateExternal(source, target, ref changeCount);
        return changeCount;
    }
}
