// <auto-generated/>

using System;

namespace OneBarker.CopyCodeGenerators.Samples;

#nullable enable
#pragma warning disable CS0109  // the member does not hide an inherited member.

partial class Mike
{
    /// <summary>
    /// Transforms the ValueToCopy value before assigning the value to the target.
    /// </summary>
    static partial void UpdateTargetTransform_ValueToCopy(ref int value);

    /// <summary>
    /// Method to run before the UpdateTarget method begins copying values.
    /// </summary>
    partial void BeforeUpdateTarget(OneBarker.CopyCodeGenerators.Samples.Mike2 target, ref int changeCount);

    /// <summary>
    /// Method to run after the UpdateTarget method finishes copying values.
    /// </summary>
    partial void AfterUpdateTarget(OneBarker.CopyCodeGenerators.Samples.Mike2 target, ref int changeCount);

    /// <summary>
    /// Updates properties in the target object from this object and returns the number of changes.
    /// </summary>
    public new int UpdateTarget(OneBarker.CopyCodeGenerators.Samples.Mike2 target)
    {
        if (ReferenceEquals(null, target)) throw new ArgumentNullException();
        if (ReferenceEquals(this, target)) return 0;
        var changeCount = 0;
        BeforeUpdateTarget(target, ref changeCount);
        var target_ValueToCopy = target.ValueToCopy;
        var this_ValueToCopy   = this.ValueToCopy;
        UpdateTargetTransform_ValueToCopy(ref this_ValueToCopy);
        if (!target_ValueToCopy.Equals(this_ValueToCopy)) {
            target.ValueToCopy = this_ValueToCopy;
            changeCount++;
        }
        AfterUpdateTarget(target, ref changeCount);
        return changeCount;
    }
}
