// <auto-generated/>

using System;

namespace OneBarker.CopyCodeGenerators.Samples;

#nullable enable
#pragma warning disable CS0109  // the member does not hide an inherited member.

partial class Tango2
{
    /// <summary>
    /// Transforms the X value before assigning the value to the target.
    /// </summary>
    partial void UpdateExternalTransform_X(ref float value);

    /// <summary>
    /// Transforms the Y value before assigning the value to the target.
    /// </summary>
    partial void UpdateExternalTransform_Y(ref float value);

    /// <summary>
    /// Transforms the Z value before assigning the value to the target.
    /// </summary>
    partial void UpdateExternalTransform_Z(ref float value);

    /// <summary>
    /// Method to run before the UpdateExternal method begins copying values.
    /// </summary>
    partial void BeforeUpdateExternal(System.Numerics.Vector2 source, ref System.Numerics.Vector3 target, ref int changeCount);

    /// <summary>
    /// Method to run after the UpdateExternal method finishes copying values.
    /// </summary>
    partial void AfterUpdateExternal(System.Numerics.Vector2 source, ref System.Numerics.Vector3 target, ref int changeCount);

    /// <summary>
    /// Updates properties from the source object to the target object and returns the number of changes.
    /// </summary>
    public new int UpdateExternal(System.Numerics.Vector2 source, ref System.Numerics.Vector3 target)
    {
        if (ReferenceEquals(null, source)) throw new ArgumentNullException();
        if (ReferenceEquals(null, target)) throw new ArgumentNullException();
        if (ReferenceEquals(target, source)) return 0;
        var changeCount = 0;
        BeforeUpdateExternal(source, ref target, ref changeCount);
        var target_X = target.X;
        var source_X = source.X;
        UpdateExternalTransform_X(ref source_X);
        if (!target_X.Equals(source_X)) {
            target.X = source_X;
            changeCount++;
        }
        var target_Y = target.Y;
        var source_Y = source.Y;
        UpdateExternalTransform_Y(ref source_Y);
        if (!target_Y.Equals(source_Y)) {
            target.Y = source_Y;
            changeCount++;
        }
        var target_Z = target.Z;
        var source_Z = Get_Z(source);
        UpdateExternalTransform_Z(ref source_Z);
        if (!target_Z.Equals(source_Z)) {
            target.Z = source_Z;
            changeCount++;
        }
        AfterUpdateExternal(source, ref target, ref changeCount);
        return changeCount;
    }
}
