// <auto-generated/>

using System;

namespace TestNamespace;

#nullable enable
#pragma warning disable CS0109 // the member does not hide an inherited member.
#pragma warning disable CS8602 // dereference of possible null reference.

partial class Vector1
{
    /// <summary>
    /// Transforms the X value before assigning the value to the target.
    /// </summary>
    partial void CopyFromTransform_X(ref float value);

    /// <summary>
    /// Method to run before the CopyFrom method begins copying values.
    /// </summary>
    partial void BeforeCopyFrom(Vector1 source);

    /// <summary>
    /// Method to run after the CopyFrom method finishes copying values.
    /// </summary>
    partial void AfterCopyFrom(Vector1 source);

    /// <summary>
    /// Copies properties from the source object to this object and returns this object.
    /// </summary>
    public new Vector1 CopyFrom(Vector1 source)
    {
        if (ReferenceEquals(null, source)) return this;
        if (ReferenceEquals(this, source)) return this;
        BeforeCopyFrom(source);
        var source_X = source.X;
        CopyFromTransform_X(ref source_X);
        this.X = source_X;
        AfterCopyFrom(source);
        return this;
    }

    /// <summary>
    /// Method to run before the CopyFrom method begins copying values.
    /// </summary>
    partial void BeforeCopyFrom(TestNamespace.Vector2 source);

    /// <summary>
    /// Method to run after the CopyFrom method finishes copying values.
    /// </summary>
    partial void AfterCopyFrom(TestNamespace.Vector2 source);

    /// <summary>
    /// Copies properties from the source object to this object and returns this object.
    /// </summary>
    public new Vector1 CopyFrom(TestNamespace.Vector2 source)
    {
        if (ReferenceEquals(null, source)) return this;
        if (ReferenceEquals(this, source)) return this;
        BeforeCopyFrom(source);
        var source_X = source.X;
        CopyFromTransform_X(ref source_X);
        this.X = source_X;
        AfterCopyFrom(source);
        return this;
    }

    /// <summary>
    /// Method to run before the CopyFrom method begins copying values.
    /// </summary>
    partial void BeforeCopyFrom(TestNamespace.Vector3 source);

    /// <summary>
    /// Method to run after the CopyFrom method finishes copying values.
    /// </summary>
    partial void AfterCopyFrom(TestNamespace.Vector3 source);

    /// <summary>
    /// Copies properties from the source object to this object and returns this object.
    /// </summary>
    public new Vector1 CopyFrom(TestNamespace.Vector3 source)
    {
        if (ReferenceEquals(null, source)) return this;
        if (ReferenceEquals(this, source)) return this;
        BeforeCopyFrom(source);
        var source_X = source.X;
        CopyFromTransform_X(ref source_X);
        this.X = source_X;
        AfterCopyFrom(source);
        return this;
    }

    /// <summary>
    /// Method to run before the CopyFrom method begins copying values.
    /// </summary>
    partial void BeforeCopyFrom(TestNamespace.Vector4 source);

    /// <summary>
    /// Method to run after the CopyFrom method finishes copying values.
    /// </summary>
    partial void AfterCopyFrom(TestNamespace.Vector4 source);

    /// <summary>
    /// Copies properties from the source object to this object and returns this object.
    /// </summary>
    public new Vector1 CopyFrom(TestNamespace.Vector4 source)
    {
        if (ReferenceEquals(null, source)) return this;
        if (ReferenceEquals(this, source)) return this;
        BeforeCopyFrom(source);
        var source_X = source.X;
        CopyFromTransform_X(ref source_X);
        this.X = source_X;
        AfterCopyFrom(source);
        return this;
    }
}
