// <auto-generated/>

using System;

namespace TestNamespace;

#nullable enable
#pragma warning disable CS0109 // the member does not hide an inherited member.
#pragma warning disable CS8602 // dereference of possible null reference.

partial class Vector4
{
    /// <summary>
    /// Transforms the W value before assigning the value to the target.
    /// </summary>
    partial void CopyFromTransform_W(ref float value);

    /// <summary>
    /// Transforms the X value before assigning the value to the target.
    /// </summary>
    partial void CopyFromTransform_X(ref float value);

    /// <summary>
    /// Transforms the Y value before assigning the value to the target.
    /// </summary>
    partial void CopyFromTransform_Y(ref float value);

    /// <summary>
    /// Transforms the Z value before assigning the value to the target.
    /// </summary>
    partial void CopyFromTransform_Z(ref float value);

    /// <summary>
    /// Method to run before the CopyFrom method begins copying values.
    /// </summary>
    partial void BeforeCopyFrom(TestNamespace.Vector3 source);

    /// <summary>
    /// Method to run after the CopyFrom method finishes copying values.
    /// </summary>
    partial void AfterCopyFrom(TestNamespace.Vector3 source);

    /// <summary>
    /// Copies properties from the source object to this object and returns this object.
    /// </summary>
    public new Vector4 CopyFrom(TestNamespace.Vector3 source)
    {
        if (ReferenceEquals(null, source)) return this;
        if (ReferenceEquals(this, source)) return this;
        BeforeCopyFrom(source);
        var source_X = source.X;
        CopyFromTransform_X(ref source_X);
        this.X = source_X;
        var source_Y = source.Y;
        CopyFromTransform_Y(ref source_Y);
        this.Y = source_Y;
        var source_Z = source.Z;
        CopyFromTransform_Z(ref source_Z);
        this.Z = source_Z;
        AfterCopyFrom(source);
        return this;
    }

    /// <summary>
    /// Method to run before the CopyFrom method begins copying values.
    /// </summary>
    partial void BeforeCopyFrom(Vector4 source);

    /// <summary>
    /// Method to run after the CopyFrom method finishes copying values.
    /// </summary>
    partial void AfterCopyFrom(Vector4 source);

    /// <summary>
    /// Copies properties from the source object to this object and returns this object.
    /// </summary>
    public new Vector4 CopyFrom(Vector4 source)
    {
        if (ReferenceEquals(null, source)) return this;
        if (ReferenceEquals(this, source)) return this;
        BeforeCopyFrom(source);
        var source_W = source.W;
        CopyFromTransform_W(ref source_W);
        this.W = source_W;
        var source_X = source.X;
        CopyFromTransform_X(ref source_X);
        this.X = source_X;
        var source_Y = source.Y;
        CopyFromTransform_Y(ref source_Y);
        this.Y = source_Y;
        var source_Z = source.Z;
        CopyFromTransform_Z(ref source_Z);
        this.Z = source_Z;
        AfterCopyFrom(source);
        return this;
    }
}
