// <auto-generated/>

using System;

namespace TestNamespace;

#nullable enable
#pragma warning disable CS0109  // the member does not hide an inherited member.

partial class Bravo2
{
    /// <summary>
    /// Transforms the NonNullableString value before assigning the value to the target.
    /// </summary>
    static partial void ConstructTransform_NonNullableString(ref string value);

    /// <summary>
    /// Method to run after the Construct method finishes copying values.
    /// </summary>
    partial void AfterConstruct(TestNamespace.Bravo source);

    /// <summary>
    /// Creates an instance of Bravo2 with values from the provided object.
    /// </summary>
    public Bravo2(TestNamespace.Bravo source)
    {
        if (ReferenceEquals(null, source)) throw new ArgumentNullException();
        var source_NonNullableString                                                  = source.NonNullableString;
        if (ReferenceEquals(null, source_NonNullableString)) source_NonNullableString = String.Empty;
        ConstructTransform_NonNullableString(ref source_NonNullableString);
        if (ReferenceEquals(null, source_NonNullableString)) source_NonNullableString = String.Empty;
        this.NonNullableString = source_NonNullableString;
        AfterConstruct(source);
    }
}
