// <auto-generated/>

using System;

namespace TestNamespace;

#nullable enable
#pragma warning disable CS0109  // the member does not hide an inherited member.

partial class Bravo
{
    /// <summary>
    /// Transforms the NonNullableString value before assigning the value to the target.
    /// </summary>
    static partial void ConstructTransform_NonNullableString(ref string value);

    /// <summary>
    /// Transforms the NullableString value before assigning the value to the target.
    /// </summary>
    static partial void ConstructTransform_NullableString(ref string? value);

    /// <summary>
    /// Method to run after the Construct method finishes copying values.
    /// </summary>
    partial void AfterConstruct(Bravo source);

    /// <summary>
    /// Creates an instance of Bravo with values from the provided object.
    /// </summary>
    public Bravo(Bravo source) : this()
    {
        if (ReferenceEquals(null, source)) throw new ArgumentNullException();
        var source_NonNullableString = source.NonNullableString;
        ConstructTransform_NonNullableString(ref source_NonNullableString);
        this.NonNullableString = source_NonNullableString;
        var source_NullableString = source.NullableString;
        ConstructTransform_NullableString(ref source_NullableString);
        this.NullableString = source_NullableString;
        AfterConstruct(source);
    }
}
