// <auto-generated/>

using System;

namespace TestNamespace;

#nullable enable
#pragma warning disable CS0109 // the member does not hide an inherited member.
#pragma warning disable CS8602 // dereference of possible null reference.

partial class Vector2
{
    /// <summary>
    /// Transforms the X value before assigning the value to the target.
    /// </summary>
    partial void ConstructTransform_X(ref float value);

    /// <summary>
    /// Transforms the Y value before assigning the value to the target.
    /// </summary>
    partial void ConstructTransform_Y(ref float value);

    /// <summary>
    /// Method to run after the Construct method finishes copying values.
    /// </summary>
    partial void AfterConstruct(System.Numerics.Vector2 source);

    /// <summary>
    /// Creates an instance of Vector2 with values from the provided object.
    /// </summary>
    public Vector2(System.Numerics.Vector2 source) : this()
    {
        if (ReferenceEquals(null, source)) return;
        var source_X = source.X;
        ConstructTransform_X(ref source_X);
        this.X = source_X;
        var source_Y = source.Y;
        ConstructTransform_Y(ref source_Y);
        this.Y = source_Y;
        AfterConstruct(source);
    }
}
