// <auto-generated/>

using System;

namespace TestNamespace;

#nullable enable
#pragma warning disable CS0109 // the member does not hide an inherited member.
#pragma warning disable CS8602 // dereference of possible null reference.

partial class Vector3
{
    /// <summary>
    /// Transforms the Name value before assigning the value to the target.
    /// </summary>
    partial void ConstructTransform_Name(ref string value);

    /// <summary>
    /// Transforms the X value before assigning the value to the target.
    /// </summary>
    partial void ConstructTransform_X(ref float value);

    /// <summary>
    /// Transforms the Y value before assigning the value to the target.
    /// </summary>
    partial void ConstructTransform_Y(ref float value);

    /// <summary>
    /// Transforms the Z value before assigning the value to the target.
    /// </summary>
    partial void ConstructTransform_Z(ref float value);

    /// <summary>
    /// Method to run after the Construct method finishes copying values.
    /// </summary>
    partial void AfterConstruct(TestNamespace.Coordinate source);

    /// <summary>
    /// Creates an instance of Vector3 with values from the provided object.
    /// </summary>
    public Vector3(TestNamespace.Coordinate source) : this()
    {
        if (ReferenceEquals(null, source)) return;
        var source_X = source.X;
        ConstructTransform_X(ref source_X);
        this.X = source_X;
        var source_Y = source.Y;
        ConstructTransform_Y(ref source_Y);
        this.Y = source_Y;
        var source_Z = source.Z;
        ConstructTransform_Z(ref source_Z);
        this.Z = source_Z;
        AfterConstruct(source);
    }

    /// <summary>
    /// Method to run after the Construct method finishes copying values.
    /// </summary>
    partial void AfterConstruct(TestNamespace.Vector2 source);

    /// <summary>
    /// Creates an instance of Vector3 with values from the provided object.
    /// </summary>
    public Vector3(TestNamespace.Vector2 source) : this()
    {
        if (ReferenceEquals(null, source)) return;
        var source_Name = source.Name;
        ConstructTransform_Name(ref source_Name);
        this.Name = source_Name;
        var source_X = source.X;
        ConstructTransform_X(ref source_X);
        this.X = source_X;
        var source_Y = source.Y;
        ConstructTransform_Y(ref source_Y);
        this.Y = source_Y;
        AfterConstruct(source);
    }

    /// <summary>
    /// Method to run after the Construct method finishes copying values.
    /// </summary>
    partial void AfterConstruct(Vector3 source);

    /// <summary>
    /// Creates an instance of Vector3 with values from the provided object.
    /// </summary>
    public Vector3(Vector3 source) : this()
    {
        if (ReferenceEquals(null, source)) return;
        var source_Name = source.Name;
        ConstructTransform_Name(ref source_Name);
        this.Name = source_Name;
        var source_X = source.X;
        ConstructTransform_X(ref source_X);
        this.X = source_X;
        var source_Y = source.Y;
        ConstructTransform_Y(ref source_Y);
        this.Y = source_Y;
        var source_Z = source.Z;
        ConstructTransform_Z(ref source_Z);
        this.Z = source_Z;
        AfterConstruct(source);
    }

    /// <summary>
    /// Method to run after the Construct method finishes copying values.
    /// </summary>
    partial void AfterConstruct(TestNamespace.Vector4 source);

    /// <summary>
    /// Creates an instance of Vector3 with values from the provided object.
    /// </summary>
    public Vector3(TestNamespace.Vector4 source) : this()
    {
        if (ReferenceEquals(null, source)) return;
        var source_Name = source.Name;
        ConstructTransform_Name(ref source_Name);
        this.Name = source_Name;
        var source_X = source.X;
        ConstructTransform_X(ref source_X);
        this.X = source_X;
        var source_Y = source.Y;
        ConstructTransform_Y(ref source_Y);
        this.Y = source_Y;
        var source_Z = source.Z;
        ConstructTransform_Z(ref source_Z);
        this.Z = source_Z;
        AfterConstruct(source);
    }
}
