// <auto-generated/>

using System;

namespace Namespace1;

#nullable enable
#pragma warning disable CS0109  // the member does not hide an inherited member.

partial class Charlie
{
    /// <summary>
    /// Transforms the Alpha value before assigning the value to the target.
    /// </summary>
    static partial void ConstructTransform_Alpha(ref int value);

    /// <summary>
    /// Method to run after the Construct method finishes copying values.
    /// </summary>
    partial void AfterConstruct(Namespace2.Charlie source);

    /// <summary>
    /// Creates an instance of Charlie with values from the provided object.
    /// </summary>
    public Charlie(Namespace2.Charlie source)
    {
        if (ReferenceEquals(null, source)) return;
        var source_Alpha = source.Alpha;
        ConstructTransform_Alpha(ref source_Alpha);
        this.Alpha = source_Alpha;
        AfterConstruct(source);
    }
}
