// <auto-generated/>

using System;

namespace OneBarker.CopyCodeGenerators.Samples;

#nullable enable
#pragma warning disable CS0109  // the member does not hide an inherited member.

partial class Mike
{
    /// <summary>
    /// Transforms the ValueToCopy value before assigning the value to the target.
    /// </summary>
    static partial void ConstructTransform_ValueToCopy(ref int value);

    /// <summary>
    /// Method to run after the Construct method finishes copying values.
    /// </summary>
    partial void AfterConstruct(Mike source);

    /// <summary>
    /// Creates an instance of Mike with values from the provided object.
    /// </summary>
    public Mike(Mike source)
    {
        if (ReferenceEquals(null, source)) throw new ArgumentNullException();
        var source_ValueToCopy = source.ValueToCopy;
        ConstructTransform_ValueToCopy(ref source_ValueToCopy);
        this.ValueToCopy = source_ValueToCopy;
        AfterConstruct(source);
    }

    /// <summary>
    /// Method to run after the Construct method finishes copying values.
    /// </summary>
    partial void AfterConstruct(OneBarker.CopyCodeGenerators.Samples.Mike2 source);

    /// <summary>
    /// Creates an instance of Mike with values from the provided object.
    /// </summary>
    public Mike(OneBarker.CopyCodeGenerators.Samples.Mike2 source)
    {
        if (ReferenceEquals(null, source)) throw new ArgumentNullException();
        var source_ValueToCopy = source.ValueToCopy;
        ConstructTransform_ValueToCopy(ref source_ValueToCopy);
        this.ValueToCopy = source_ValueToCopy;
        AfterConstruct(source);
    }
}
