// <auto-generated/>

using System;

namespace TestNamespace;

#nullable enable
#pragma warning disable CS0109  // the member does not hide an inherited member.

partial class Bravo2
{
    /// <summary>
    /// Transforms the NonNullableString value before assigning the value to the target.
    /// </summary>
    static partial void UpdateFromTransform_NonNullableString(ref string value);

    /// <summary>
    /// Method to run before the UpdateFrom method begins copying values.
    /// </summary>
    partial void BeforeUpdateFrom(TestNamespace.Bravo source, ref int changeCount);

    /// <summary>
    /// Method to run after the UpdateFrom method finishes copying values.
    /// </summary>
    partial void AfterUpdateFrom(TestNamespace.Bravo source, ref int changeCount);

    /// <summary>
    /// Updates properties from the source object to this object and returns the number of changes.
    /// </summary>
    public new int UpdateFrom(TestNamespace.Bravo source)
    {
        if (ReferenceEquals(null, source)) throw new ArgumentNullException();
        if (ReferenceEquals(this, source)) return 0;
        var changeCount = 0;
        BeforeUpdateFrom(source, ref changeCount);
        var this_NonNullableString                                                    = this.NonNullableString;
        var source_NonNullableString                                                  = source.NonNullableString;
        if (ReferenceEquals(null, source_NonNullableString)) source_NonNullableString = String.Empty;
        UpdateFromTransform_NonNullableString(ref source_NonNullableString);
        if (ReferenceEquals(null, source_NonNullableString)) source_NonNullableString = String.Empty;
        if (!ReferenceEquals(this_NonNullableString, source_NonNullableString) && (ReferenceEquals(null, this_NonNullableString) || !this_NonNullableString.Equals(source_NonNullableString))) {
            this.NonNullableString = source_NonNullableString;
            changeCount++;
        }
        AfterUpdateFrom(source, ref changeCount);
        return changeCount;
    }
}
