// <auto-generated/>

using System;

namespace OneBarker.CopyCodeGenerators.Samples;

#nullable enable
#pragma warning disable CS0109  // the member does not hide an inherited member.

partial class Mike
{
    /// <summary>
    /// Transforms the ValueToCopy value before assigning the value to the target.
    /// </summary>
    static partial void CopyToTransform_ValueToCopy(ref int value);

    /// <summary>
    /// Method to run before the CopyTo method begins copying values.
    /// </summary>
    partial void BeforeCopyTo(OneBarker.CopyCodeGenerators.Samples.Mike2 target);

    /// <summary>
    /// Method to run after the CopyTo method finishes copying values.
    /// </summary>
    partial void AfterCopyTo(OneBarker.CopyCodeGenerators.Samples.Mike2 target);

    /// <summary>
    /// Copies properties from this object to the target object and returns the target object.
    /// </summary>
    public new Mike CopyTo(OneBarker.CopyCodeGenerators.Samples.Mike2 target)
    {
        if (ReferenceEquals(null, target)) throw new ArgumentNullException();
        BeforeCopyTo(target);
        var this_ValueToCopy = this.ValueToCopy;
        CopyToTransform_ValueToCopy(ref this_ValueToCopy);
        target.ValueToCopy = this_ValueToCopy;
        AfterCopyTo(target);
        return this;
    }
}
