// <auto-generated/>

using System;

namespace TestNamespace;

#nullable enable
#pragma warning disable CS0109  // the member does not hide an inherited member.

partial class Alpha
{
    /// <summary>
    /// Transforms the Value value before assigning the value to the target.
    /// </summary>
    static partial void UpdateFromTransform_Value(ref int value);

    /// <summary>
    /// Method to run before the UpdateFrom method begins copying values.
    /// </summary>
    partial void BeforeUpdateFrom(Alpha source, ref int changeCount);

    /// <summary>
    /// Method to run after the UpdateFrom method finishes copying values.
    /// </summary>
    partial void AfterUpdateFrom(Alpha source, ref int changeCount);

    /// <summary>
    /// Updates properties from the source object to this object and returns the number of changes.
    /// </summary>
    public new int UpdateFrom(Alpha source)
    {
        if (ReferenceEquals(null, source)) throw new ArgumentNullException();
        if (ReferenceEquals(this, source)) return 0;
        var changeCount = 0;
        BeforeUpdateFrom(source, ref changeCount);
        var this_Value   = this.Value;
        var source_Value = source.Value;
        UpdateFromTransform_Value(ref source_Value);
        if (!this_Value.Equals(source_Value)) {
            this.Value = source_Value;
            changeCount++;
        }
        AfterUpdateFrom(source, ref changeCount);
        return changeCount;
    }
}
