// <auto-generated/>

using System;

namespace OneBarker.CopyCodeGenerators.Samples;

#nullable enable
#pragma warning disable CS0109  // the member does not hide an inherited member.

partial class Mike
{
    /// <summary>
    /// Transforms the ValueToCopy value before assigning the value to the target.
    /// </summary>
    static partial void CopyFromTransform_ValueToCopy(ref int value);

    /// <summary>
    /// Method to run before the CopyFrom method begins copying values.
    /// </summary>
    partial void BeforeCopyFrom(Mike source);

    /// <summary>
    /// Method to run after the CopyFrom method finishes copying values.
    /// </summary>
    partial void AfterCopyFrom(Mike source);

    /// <summary>
    /// Copies properties from the source object to this object and returns this object.
    /// </summary>
    public new Mike CopyFrom(Mike source)
    {
        if (ReferenceEquals(null, source)) throw new ArgumentNullException();
        if (ReferenceEquals(this, source)) return this;
        BeforeCopyFrom(source);
        var source_ValueToCopy = source.ValueToCopy;
        CopyFromTransform_ValueToCopy(ref source_ValueToCopy);
        this.ValueToCopy = source_ValueToCopy;
        AfterCopyFrom(source);
        return this;
    }

    /// <summary>
    /// Method to run before the CopyFrom method begins copying values.
    /// </summary>
    partial void BeforeCopyFrom(OneBarker.CopyCodeGenerators.Samples.Mike2 source);

    /// <summary>
    /// Method to run after the CopyFrom method finishes copying values.
    /// </summary>
    partial void AfterCopyFrom(OneBarker.CopyCodeGenerators.Samples.Mike2 source);

    /// <summary>
    /// Copies properties from the source object to this object and returns this object.
    /// </summary>
    public new Mike CopyFrom(OneBarker.CopyCodeGenerators.Samples.Mike2 source)
    {
        if (ReferenceEquals(null, source)) throw new ArgumentNullException();
        if (ReferenceEquals(this, source)) return this;
        BeforeCopyFrom(source);
        var source_ValueToCopy = source.ValueToCopy;
        CopyFromTransform_ValueToCopy(ref source_ValueToCopy);
        this.ValueToCopy = source_ValueToCopy;
        AfterCopyFrom(source);
        return this;
    }
}
