// <auto-generated/>

using System;

namespace OneBarker.CopyCodeGenerators.Samples;

#nullable enable
#pragma warning disable CS0109  // the member does not hide an inherited member.

partial struct Juliet
{
    /// <summary>
    /// Transforms the Name value before assigning the value to the target.
    /// </summary>
    static partial void ConstructTransform_Name(ref string? value);

    /// <summary>
    /// Transforms the X value before assigning the value to the target.
    /// </summary>
    static partial void ConstructTransform_X(ref float value);

    /// <summary>
    /// Transforms the Y value before assigning the value to the target.
    /// </summary>
    static partial void ConstructTransform_Y(ref float value);

    /// <summary>
    /// Method to run after the Construct method finishes copying values.
    /// </summary>
    partial void AfterConstruct(OneBarker.CopyCodeGenerators.Samples.Juliet2 source);

    /// <summary>
    /// Creates an instance of Juliet with values from the provided object.
    /// </summary>
    public Juliet(OneBarker.CopyCodeGenerators.Samples.Juliet2 source)
    {
        if (ReferenceEquals(null, source)) throw new ArgumentNullException();
        var source_Name = source.Name;
        ConstructTransform_Name(ref source_Name);
        this.Name = source_Name;
        var source_X = source.X;
        ConstructTransform_X(ref source_X);
        this.X = source_X;
        var source_Y = source.Y;
        ConstructTransform_Y(ref source_Y);
        this.Y = source_Y;
        AfterConstruct(source);
    }
}
