using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace OneBarker.CopyCodeGenerators
{
    [Generator]
    public class UpdateExternalSourceGenerator : IIncrementalGenerator
    {
        private const string Namespace     = "Generators";
        private const string AttributeName = "EnableUpdateExternalAttribute";

        private const string AttributeSourceCode = @"// <auto-generated/>

using System;

namespace " + Namespace + @"
{
    /// <summary>
    /// Generates an UpdateExternal method taking the provided SourceType and TargetType as arguments. 
    /// </summary>
    [System.AttributeUsage(System.AttributeTargets.Class | System.AttributeTargets.Struct, AllowMultiple = true)]
    internal class " + AttributeName + @" : Attribute
    {
        public Type SourceType { get; }
        public Type TargetType { get; }
        
        public " + AttributeName + @"(Type sourceType, Type targetType)
        {
            SourceType = sourceType;
            TargetType = targetType;
        }
    }
}";

        private const string FullAttributeName = Namespace + "." + AttributeName;

        private readonly CopyCodeGenerator _generator = new CopyCodeGenerator(
            (target, source, param1, param2, set)
                => $"public new int UpdateExternal({source} {param1}, {target} {param2})",
            (target, source, set)
                => "Updates properties from the source object to the target object and returns the number of changes.",
            "UpdateExternal",
            CopyCodeGenerator.MethodReturnType.Count,
            addBeforeMethod: true,
            addAfterMethod: true,
            useSecondTypeFromAttribute: true
        );
        
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            // Add the marker attribute to the compilation.
            context.RegisterPostInitializationOutput(
                ctx => ctx.AddSource(
                    $"{AttributeName}.g.cs",
                    SourceText.From(AttributeSourceCode, Encoding.UTF8)
                )
            );

            // Filter classes annotated with the attribute. Only filtered Syntax Nodes can trigger code generation.
            var provider = context.SyntaxProvider
                                  .CreateSyntaxProvider(
                                      (s,   _) => s is ClassDeclarationSyntax || s is StructDeclarationSyntax,
                                      (ctx, _) => ctx.GetCopyClassDeclarationSetForSourceGen(FullAttributeName)
                                  )
                                  .Where(t => t.AttributeFound)
                                  .Select((t, _) => t);

            // Generate the source code.
            context.RegisterSourceOutput(
                context.CompilationProvider.Combine(provider.Collect()),
                (ctx, t) => _generator.Generate(ctx, t.Left, t.Right)
            );
        }
    }
}
