// <auto-generated/>

using System;

namespace OneBarker.CopyCodeGenerators.Samples;

#nullable enable
#pragma warning disable CS0109  // the member does not hide an inherited member.

partial class Hotel
{
    /// <summary>
    /// Transforms the X value before assigning the value to the target.
    /// </summary>
    static partial void ConstructTransform_X(ref float value);

    /// <summary>
    /// Transforms the Y value before assigning the value to the target.
    /// </summary>
    static partial void ConstructTransform_Y(ref float value);

    /// <summary>
    /// Transforms the Z value before assigning the value to the target.
    /// </summary>
    static partial void ConstructTransform_Z(ref float value);

    /// <summary>
    /// Method to run after the Construct method finishes copying values.
    /// </summary>
    partial void AfterConstruct(Hotel source);

    /// <summary>
    /// Creates an instance of Hotel with values from the provided object.
    /// </summary>
    public Hotel(Hotel source) : this()
    {
        if (ReferenceEquals(null, source)) throw new ArgumentNullException();
        var source_X = source.X;
        ConstructTransform_X(ref source_X);
        this.X = source_X;
        var source_Y = source.Y;
        ConstructTransform_Y(ref source_Y);
        this.Y = source_Y;
        var source_Z = source.Z;
        ConstructTransform_Z(ref source_Z);
        this.Z = source_Z;
        AfterConstruct(source);
    }

    /// <summary>
    /// Method to run after the Construct method finishes copying values.
    /// </summary>
    partial void AfterConstruct(OneBarker.CopyCodeGenerators.Samples.IHotel source);

    /// <summary>
    /// Creates an instance of Hotel with values from the provided object.
    /// </summary>
    public Hotel(OneBarker.CopyCodeGenerators.Samples.IHotel source) : this()
    {
        if (ReferenceEquals(null, source)) throw new ArgumentNullException();
        var source_X = source.X;
        ConstructTransform_X(ref source_X);
        this.X = source_X;
        var source_Y = source.Y;
        ConstructTransform_Y(ref source_Y);
        this.Y = source_Y;
        var source_Z = source.Z;
        ConstructTransform_Z(ref source_Z);
        this.Z = source_Z;
        AfterConstruct(source);
    }
}
