// <auto-generated/>

using System;

namespace OneBarker.CopyCodeGenerators.Samples;

#nullable enable
#pragma warning disable CS0109  // the member does not hide an inherited member.

partial record Echo
{
    /// <summary>
    /// Transforms the Age value and returns the new value.
    /// </summary>
    static int PassthroughTransform_Age(OneBarker.CopyCodeGenerators.Samples.Echo2 source)
    {
        if (ReferenceEquals(null, source)) throw new ArgumentNullException();
        var value = source.Age;
        ConstructTransform_Age(ref value);
        return value;
    }

    /// <summary>
    /// Transforms the Name value and returns the new value.
    /// </summary>
    static string PassthroughTransform_Name(OneBarker.CopyCodeGenerators.Samples.Echo2 source)
    {
        if (ReferenceEquals(null, source)) throw new ArgumentNullException();
        var value = source.Name;
        ConstructTransform_Name(ref value);
        return value;
    }

    /// <summary>
    /// Transforms the Age value before assigning the value to the target.
    /// </summary>
    static partial void ConstructTransform_Age(ref int value);

    /// <summary>
    /// Transforms the Name value before assigning the value to the target.
    /// </summary>
    static partial void ConstructTransform_Name(ref string value);

    /// <summary>
    /// Method to run after the Construct method finishes copying values.
    /// </summary>
    partial void AfterConstruct(Echo source);

    /// <summary>
    /// Creates an instance of Echo with values from the provided object.
    /// </summary>
    public Echo(Echo source)
    {
        if (ReferenceEquals(null, source)) throw new ArgumentNullException();
        var source_Age = source.Age;
        ConstructTransform_Age(ref source_Age);
        this.Age = source_Age;
        var source_Name = source.Name;
        ConstructTransform_Name(ref source_Name);
        this.Name = source_Name;
        AfterConstruct(source);
    }

    /// <summary>
    /// Method to run after the Construct method finishes copying values.
    /// </summary>
    partial void AfterConstruct(OneBarker.CopyCodeGenerators.Samples.Echo2 source);

    /// <summary>
    /// Creates an instance of Echo with values from the provided object.
    /// </summary>
    public Echo(OneBarker.CopyCodeGenerators.Samples.Echo2 source) : this(PassthroughTransform_Name(source), PassthroughTransform_Age(source))
    {
        if (ReferenceEquals(null, source)) throw new ArgumentNullException();
        AfterConstruct(source);
    }
}
