// <auto-generated/>

using System;

namespace OneBarker.CopyCodeGenerators.Samples;

#nullable enable
#pragma warning disable CS0109  // the member does not hide an inherited member.

partial record Delta
{
    /// <summary>
    /// Transforms the Age value before assigning the value to the target.
    /// </summary>
    static partial void ConstructTransform_Age(ref int value);

    /// <summary>
    /// Transforms the Name value before assigning the value to the target.
    /// </summary>
    static partial void ConstructTransform_Name(ref string value);

    /// <summary>
    /// Method to run after the Construct method finishes copying values.
    /// </summary>
    partial void AfterConstruct(Delta source);

    /// <summary>
    /// Creates an instance of Delta with values from the provided object.
    /// </summary>
    public Delta(Delta source)
    {
        if (ReferenceEquals(null, source)) throw new ArgumentNullException();
        var source_Age = source.Age;
        ConstructTransform_Age(ref source_Age);
        this.Age = source_Age;
        var source_Name = source.Name;
        ConstructTransform_Name(ref source_Name);
        this.Name = source_Name;
        AfterConstruct(source);
    }

    /// <summary>
    /// Method to run after the Construct method finishes copying values.
    /// </summary>
    partial void AfterConstruct(OneBarker.CopyCodeGenerators.Samples.Delta2 source);

    /// <summary>
    /// Creates an instance of Delta with values from the provided object.
    /// </summary>
    public Delta(OneBarker.CopyCodeGenerators.Samples.Delta2 source) : this()
    {
        if (ReferenceEquals(null, source)) throw new ArgumentNullException();
        var source_Age = source.Age;
        ConstructTransform_Age(ref source_Age);
        this.Age = source_Age;
        var source_Name = source.Name;
        ConstructTransform_Name(ref source_Name);
        this.Name = source_Name;
        AfterConstruct(source);
    }
}
