// <auto-generated/>

using System;

namespace OneBarker.CopyCodeGenerators.Samples;

#nullable enable
#pragma warning disable CS0109  // the member does not hide an inherited member.

partial class November
{
    /// <summary>
    /// Transforms the NonNullableString value before assigning the value to the target.
    /// </summary>
    static partial void UpdateTargetTransform_NonNullableString(ref string value);

    /// <summary>
    /// Transforms the Value1 value before assigning the value to the target.
    /// </summary>
    static partial void UpdateTargetTransform_Value1(ref int value);

    /// <summary>
    /// Transforms the Value2 value before assigning the value to the target.
    /// </summary>
    static partial void UpdateTargetTransform_Value2(ref int value);

    /// <summary>
    /// Method to run before the UpdateTarget method begins copying values.
    /// </summary>
    partial void BeforeUpdateTarget(OneBarker.CopyCodeGenerators.Samples.November2 target, ref int changeCount);

    /// <summary>
    /// Method to run after the UpdateTarget method finishes copying values.
    /// </summary>
    partial void AfterUpdateTarget(OneBarker.CopyCodeGenerators.Samples.November2 target, ref int changeCount);

    /// <summary>
    /// Updates properties in the target object from this object and returns the number of changes.
    /// </summary>
    public new int UpdateTarget(OneBarker.CopyCodeGenerators.Samples.November2 target)
    {
        if (ReferenceEquals(null, target)) throw new ArgumentNullException();
        if (ReferenceEquals(this, target)) return 0;
        var changeCount = 0;
        BeforeUpdateTarget(target, ref changeCount);
        var target_NonNullableString = target.NonNullableString;
        var this_NonNullableString = this.Get_NonNullableString();
        if (ReferenceEquals(null, this_NonNullableString)) this_NonNullableString = String.Empty;
        UpdateTargetTransform_NonNullableString(ref this_NonNullableString);
        if (ReferenceEquals(null, this_NonNullableString)) this_NonNullableString = String.Empty;
        if (!ReferenceEquals(target_NonNullableString, this_NonNullableString) && (ReferenceEquals(null, target_NonNullableString) || !target_NonNullableString.Equals(this_NonNullableString))) {
            target.NonNullableString = this_NonNullableString;
            changeCount++;
        }
        var target_Value1 = target.Value1;
        var this_Value1 = this._value1;
        UpdateTargetTransform_Value1(ref this_Value1);
        if (!target_Value1.Equals(this_Value1)) {
            target.Value1 = this_Value1;
            changeCount++;
        }
        var target_Value2 = target.Value2;
        var this_Value2 = this.Get_Value2();
        UpdateTargetTransform_Value2(ref this_Value2);
        if (!target_Value2.Equals(this_Value2)) {
            target.Value2 = this_Value2;
            changeCount++;
        }
        AfterUpdateTarget(target, ref changeCount);
        return changeCount;
    }
}
