// <auto-generated/>

using System;

namespace TestNamespace;

#nullable enable
#pragma warning disable CS0109  // the member does not hide an inherited member.

partial class Bravo
{
    /// <summary>
    /// Transforms the NonNullableString value before assigning the value to the target.
    /// </summary>
    static partial void CopyFromTransform_NonNullableString(ref string value);

    /// <summary>
    /// Transforms the NullableString value before assigning the value to the target.
    /// </summary>
    static partial void CopyFromTransform_NullableString(ref string? value);

    /// <summary>
    /// Method to run before the CopyFrom method begins copying values.
    /// </summary>
    partial void BeforeCopyFrom(Bravo source);

    /// <summary>
    /// Method to run after the CopyFrom method finishes copying values.
    /// </summary>
    partial void AfterCopyFrom(Bravo source);

    /// <summary>
    /// Copies properties from the source object to this object and returns this object.
    /// </summary>
    public new Bravo CopyFrom(Bravo source)
    {
        if (ReferenceEquals(null, source)) throw new ArgumentNullException();
        if (ReferenceEquals(this, source)) return this;
        BeforeCopyFrom(source);
        var source_NonNullableString = source.NonNullableString;
        CopyFromTransform_NonNullableString(ref source_NonNullableString);
        this.NonNullableString = source_NonNullableString;
        var source_NullableString = source.NullableString;
        CopyFromTransform_NullableString(ref source_NullableString);
        this.NullableString = source_NullableString;
        AfterCopyFrom(source);
        return this;
    }
}
