// <auto-generated/>

using System;

namespace TestNamespace;

#nullable enable
#pragma warning disable CS0109  // the member does not hide an inherited member.

partial class Bravo2
{
    /// <summary>
    /// Transforms the NonNullableString value before assigning the value to the target.
    /// </summary>
    static partial void CopyFromTransform_NonNullableString(ref string value);

    /// <summary>
    /// Method to run before the CopyFrom method begins copying values.
    /// </summary>
    partial void BeforeCopyFrom(TestNamespace.Bravo source);

    /// <summary>
    /// Method to run after the CopyFrom method finishes copying values.
    /// </summary>
    partial void AfterCopyFrom(TestNamespace.Bravo source);

    /// <summary>
    /// Copies properties from the source object to this object and returns this object.
    /// </summary>
    public new Bravo2 CopyFrom(TestNamespace.Bravo source)
    {
        if (ReferenceEquals(null, source)) throw new ArgumentNullException();
        if (ReferenceEquals(this, source)) return this;
        BeforeCopyFrom(source);
        var source_NonNullableString                                                  = source.NonNullableString;
        if (ReferenceEquals(null, source_NonNullableString)) source_NonNullableString = String.Empty;
        CopyFromTransform_NonNullableString(ref source_NonNullableString);
        if (ReferenceEquals(null, source_NonNullableString)) source_NonNullableString = String.Empty;
        this.NonNullableString = source_NonNullableString;
        AfterCopyFrom(source);
        return this;
    }
}
